version: "3.9"

services:
  backend:
    stdin_open: true
    container_name: xfitness-backend
    hostname: backend
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src:/app/src
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DB_HOST=host.docker.internal
      - DB_NAME=xfitness-local
      - DB_USER=username
      - DB_PASSWORD=password
      - DB_PORT=5432